# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: custom
  theme_night: custom
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
  verification:
    google: 'sdqtCzyYSpt0or-ovQuZS1n7vRVRODf-y7blThHOjMM'
    
# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

footer:
  copyright:
    notice: '© {year} Kieran Klukas. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

security:
  csp:
    policy: "default-src 'self'; script-src 'report-sample' 'self' https://analytics.kieranklukas.com/js/script.outbound-links.js https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js https://cdn.jsdelivr.net/npm/mathjax@3/es5/input/tex/extensions/noerrors.js https://cdn.jsdelivr.net/gh/krisk/Fuse@v3.2.1/dist/fuse.min.js https://cdn.jsdelivr.net/gh/julmot/mark.js@8.11.1/dist/jquery.mark.min.js https://giscus.app/client.js https://www.google.com/recaptcha/api.js https://www.gstatic.com/recaptcha/releases/gEr-ODersURoIfof1hiDm7R5/recaptcha__en.js https://identity.netlify.com/v1/netlify-identity-widget.js https://kieranklukas.com/cdn-cgi/challenge-platform/h/b/scripts/pica.js; style-src 'report-sample' 'self' https://fonts.googleapis.com; object-src 'none'; base-uri 'self'; connect-src 'self' https://analytics.kieranklukas.com; font-src 'self' https://cdn.jsdelivr.net https://fonts.gstatic.com; frame-src 'self' https://www.google.com; img-src 'self'; manifest-src 'self'; media-src 'self'; report-uri https://63deebdde3076651bce70e3d.endpoint.csper.io/?v=1; worker-src 'none'"
    report_only: true

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/kcoderhtml/blog'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'giscus'
    giscus:
      repo: 'kcoderhtml/blog-comments'
      repo_id: 'R_kgDOI48RPg'
      category: 'Announcements'
      category_id: 'DIC_kwDOI48RPs4CT9Ou'
      data-loading: 'lazy'
      theme: 'transparent_dark'
  search:
    provider: wowchemy
  map:
    provider: ''
    api_key: ''
    zoom: 15
